spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    check-template: true
    check-template-location: true
    fail-fast: true
    encoding: UTF-8